services:
  - type: web
    name: characterverse
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: characterverse-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://characterverse.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: characterverse-db
    databaseName: characterverse
    plan: free
