services:
  - type: web
    name: characterverse
    env: node
    plan: free
    region: oregon # Choose closest to your users
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: characterverse-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://characterverse.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false # Set manually in dashboard for security
    
    # Auto-deploy on git push
    autoDeploy: true
    
    # Custom build settings
    buildFilter:
      paths:
        - src/**
        - prisma/**
        - package.json
        - next.config.js
    
databases:
  - name: characterverse-db
    plan: free
    databaseName: characterverse
    user: characterverse_user
    region: oregon
    
    # Backup settings (paid plans only)
    # postgresMajorVersion: 15
